version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/thumbor-mongo-storage

    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: 'Install py plugin'
          command: 'sudo pip install pymongo'
      - run:
          name: build
          command: 'python -m compileall tc_mongodb/storages/mongo_storage.py'
